# Generated by Django 4.1.3 on 2023-01-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('Interaction_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Protein_ID_A', models.CharField(max_length=20)),
                ('Protein_ID_B', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('RID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Protein_Name', models.CharField(max_length=20)),
                ('Organism_Name', models.CharField(max_length=50)),
                ('Protein_ID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Interaction_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
